### ISSUE TITLE
Some parts of the UI are black and probably shouldn't be (gedit & backup)

### ISSUE THREAD

**Issue by vitalykorolev** [numixproject/numix-gtk-theme#121]
(In Ubuntu 14.04 LTS)
1: Backup app (System Settings > Backups > Back Up Now...) shows some backgrounds in black which looks bad.
![screenshot from 2014-04-23 08 41 40](https://cloud.githubusercontent.com/assets/1957746/2780823/8233623a-cb0c-11e3-9cf7-ee3b1c6b7d32.png)

2: Gedit has a black background behind tabbar and when all tabs are closed.
![screenshot from 2014-04-23 08 42 15](https://cloud.githubusercontent.com/assets/1957746/2780827/8d940fa8-cb0c-11e3-8b6d-0edb9a1d650c.png)
![screenshot from 2014-04-23 08 42 24](https://cloud.githubusercontent.com/assets/1957746/2780831/90eebf4a-cb0c-11e3-9f3b-959dec7d83b4.png)

**Comment by sergeyhoh** [comment]
For Ubuntu 14.04, I added the following in /usr/share/themes/Numix/gtk-3.0/gtk-widgets.css,

```
GtkWindow {
    color: @fg_color;
    background-color: @bg_color;
}
GtkPaned {
    background-color: @bg_color;
}
GtkEventBox {
    background-color: @bg_color;
}
```

and, it fixed a black background.

**Comment by satya164** [comment]
@PaoloRotolo isn't the overlay-scrollbar patch included yet?

**Comment by satya164** [comment]
BTW disable overlay scrollbars and the bug should be gone.

**Comment by harsesus** [comment]
I am in version: 

2.2+294~201404231512~ubuntu14.04.1

Not sure if the fix just hasn't gotten down to me yet.  I have the issue, and it also causes nemo to go all black.  Not sure if nautilus does it as well.  It seems to be tied to certain events, one of which I think is 'apt-get update'.

Here is a screenshot: https://i.imgur.com/DsyYfrd.png

**Comment by satya164** [comment]
@harsesus As said above, the bug is caused due to overlay-scrollbars. Please disable overlay scrollbars to fix it.

**Comment by vitalykorolev** [comment]
@satya164 what you're suggesting is a workaround and not a fix.
Problem with gedit is gone with the latest update from PPA. However backup app is still showing blacks in weird places like shown in the screenshot.

**Comment by satya164** [comment]
@vitalykorolev Yes. But the bug is in overlay scrollbars. I'm doing whatever I can to fix this at theme level by using hacky ways. This bug should be really fixed in overlay scrollbar level, and not in themes.

https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/1059374

**Comment by vitalykorolev** [comment]
@satya164 I see your point. How does default Ambiance theme avoids this issue?
By the way, today's PPA update brought back the black in gedit. :(

**Comment by satya164** [comment]
@vitalykorolev Ambiance uses a hacky way by setting bg color for universal selector. We use patches to do that for Ubuntu. Prolly patches failed today. Will check.

**Comment by Tammuz** [comment]
I can confirm this issue, using comment 2 solution fixes the problem.

**Comment by pinumbernumber** [comment]
This is still present, comment 2 still fixes it.

(Disabling overlay scrollbar also fixes it, but I'd prefer to keep them)

**Comment by satya164** [comment]
Well, it's a bug with overlay scrollbars, and it's canonical's
responsibility to fix. The bug was reported long back and still hasn't been
fixed.

**Comment by pinumbernumber** [comment]
Fair enough, I can understand not wanting to add hacks for one particular distro.

(They probably won't fix it, though, and Unity is popular, so it might be pragmatic to add it if it doesn't negatively affect anything else.

Alternatively, what about having the installation script in the Ubuntu PPA packages adding the hacky fix to the file after the fact? That way it doesn't need to be upstream.)

**Comment by satya164** [comment]
We had a patch for Ubuntu in the PPA. It's failing for some reason. We'll
check why.

On 1 October 2014 01:10, pinumbernumber notifications@github.com wrote:

> Fair enough, I can understand not wanting to add hacks for one particular
> distro.
> 
> (They probably won't fix it, though, and Unity is popular, so it might be
> pragmatic to add it if it doesn't negatively affect anything else.
> 
> Alternatively, what about having the installation script in the Ubuntu PPA
> packages adding the hacky fix to the file after the fact? That way it
> doesn't need to be upstream.)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shimmerproject/Numix/issues/121#issuecomment-57370475
> .

## 

Satyajit Sahoo
Digital artist
DeviantArt Profile http://satya164.deviantart.com

We're all stories, in the end. Just make it a good one, eh? — The Doctor,
Season 5, Episode 13.

**Comment by khurshid-alam** [comment]
@satya164 

> We had a patch for Ubuntu in the PPA. It's failing for some reason.

What do you mean by that? Is it included or is it not? Can you tell me what exactly the patch is (or provide me a link to patch)? AFAIK it is to add a global inherit color to base states of gtk-widgets.css. `* {
    /* inherit colors from parent */
    color: inherit;
    background-color: inherit;
}` Right? Or is it something else?

I have reported again again that even though it seems that the issue is with overlay scrollbar, it may not have to be the only issue. Gtk+ breaks themes so often that it is hard to figure out what it was exactly. As far I remember all these started with introduction with gtk-headerbar & compiz (& unity window decorator) in Ubuntu still does not have support for headerbar.

I have tested with two separate version of Numix (on Ubuntu 14.10), Numix 1.8 from repo & the ppa version. I can confirm that even with the hack (if it is applied on repo & ppa), it still shows black bar in some areas (for both versions).

Screenshot:

![image-1](http://i.imgur.com/zHnLA5L.png)

However, I have old numix theme (probably before this commit: https://github.com/shimmerproject/Numix/commit/c3a8c0a39863f4520807944eaf88ac1b688fac7a) which was still using old tab design & light gtk-headerbar & titlebar. With that theme, **there is no black area or  no black bar at all even with overlay-scrollbar**.

Screenshots:

![image-2](http://i.imgur.com/RSlVT7O.png)
![image-3](http://i.imgur.com/2dAI4E7.png)

So, how exactly was is working with overlay-scrollbar? Everything seems so perfect with the theme except toolbar-menu button which is normal because at the point it was still shaping up for 3.12.

If you want I can give you the diff between gtk-widget.css (old & new). I really want to get this bug fixed permanently.

**Comment by vitalykorolev** [comment]
+1 for @khurshid-alam

**Comment by jxu** [comment]
I still have the black bar issue with gedit with Ubuntu 14.04. https://github.com/numixproject/numix-gtk-theme/issues/121#issuecomment-41266145 fixed it.
